language: ruby

rvm:
  - 2.2.2
  - 2.3.1
  - jruby-22mode

script:
  - bundle exec rake ci

sudo: false

env:
  global:
    # To allow JRUBY to install c-extension gems
    - "JRUBY_OPTS=-Xcext.enabled=true"
