language: ruby

rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2.2
  - 2.3.1
  - jruby-19mode
  - jruby-head

script:
  - bundle exec rake ci

sudo: false

env:
  global:
    # To allow JRUBY to install c-extension gems
    - "JRUBY_OPTS=-Xcext.enabled=true"
